steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
#- name: 'gcr.io/cloud-builders/npm'
#  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/kube-frontend:$REVISION_ID", "."]
#- name: 'gcr.io/cloud-builders/docker'
#  args: ["push", "gcr.io/$PROJECT_ID/kube-frontend:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker push gcr.io/$PROJECT_ID/kube-frontend:$REVISION_ID
#    [[ "$BRANCH_NAME" == "master" ]] && docker push gcr.io/$PROJECT_ID/kube-frontend:$REVISION_ID || echo "skipping . . ."
#- name: 'gcr.io/cloud-builders/kubectl'
#  args:
#  - 'set'
#  - 'image'
#  - 'deployment/kube-frontend'
#  - 'kube-frontend=gcr.io/$PROJECT_ID/kube-frontend:$REVISION_ID'
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && kubectl set image deployment/kube-frontend kube-frontend=gcr.io/$PROJECT_ID/kube-frontend:$REVISION_ID || echo "skipping . . ."
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'